### ISSUE TITLE
No warning/error when applied wrongly?

### ISSUE THREAD

**Issue by BaptisteSadoughi** [annaplaksienko/methyLImp2#1]
Dear authors of methylLimp2,

I am applying the package to impute methylation values from rrbs data, by specifying type = "user", and providing a chromosome annotation file. The data matrix has samples as rows and cpg as columns. I was surprised that the function ran despite the fact that all the rows (i.e. samples, observations) include at least one NA.

I was wondering if I should be expecting an error message or if I misunderstand something from the articles?

Thank you in advance!
Best

**Comment by annaplaksienko** [comment]
Hi @BaptisteSadoughi! Sorry for a very late reply. If there is at least one NA in every CpG, then yes, methyLImp can't conduct imputation. But if that's the case for every sample, that's fine!

Let me know if there is anything else I can help you with!

**Comment by BaptisteSadoughi** [comment]
Ah ok so it's a requirement on the CpGs and not the samples. Thanks for your reply!

**Comment by annaplaksienko** [comment]
Exactly. And it's not a strict requirement if you think about it: if you have tens of thousands of CpGs and ALL have at least one NA, you should check the quality of samples or the machine 😬
